version: "3.8"

services:
  app:
    image: production-pandarium-app
    build:
      dockerfile: Dockerfile.production
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://db/pandarium
  db:
    image: mongo:6.0.4-jammy
    ports:
      - 27017:27017
    volumes:
      - pandarium:/data/db

volumes:
  pandarium: 