import Head from 'next/head'
import Image from 'next/image'

export default function LandingPage() {
  return (	
		<>
			<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
			</Head>
      <h1 className="text-4xl font-rubikbold uppercase">Graj z dowolnego urządzenia</h1>
		</>
	)
}
