import Button from 'components/Global/Button';
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { io } from "socket.io-client"

export default function LandingPage() {

  let socket = io();

  const [input, setInput] = useState('');
  const [input2, setInput2] = useState('');
  const [mess, setMess] = useState<string[]>([]);

  const socketInitializer = async () => {

    await fetch('/api/socket');

    socket.on('connect', () => {
      console.log('connected');
    })

    socket.on('update-input', msg => {
      setInput(msg);
    })

    socket.on('update-mess', msg => {
      setMess(msg);
    })



    return null

  }

  const onChangeHandler = (e: any) => {

    setInput(e.target.value);
    // socket.emit('input-change', e.target.value);

  }
  
  const onChangeHandler2 = (e: any) => {

    setInput2(e.target.value);
    // socket.emit('input-change', e.target.value);

  }

  const btnHandler = () => {

    var today = new Date();
    let toPut = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds()+" "+input2+" -> "+input;
    setMess(
      [
        ...mess,
        toPut
      ]
    );

    socket.emit('sended', [...mess, toPut]);

  }

  const clearHandler = () => {

    setMess([]);

    socket.emit('sended', mess);

  }

  useEffect(() => {

    socketInitializer();

  }, [])
  
  return (	
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex w-full h-full px-4">
				<div className="mx-auto my-24 flex flex-wrap gap-4">

					Jakaś tam historia:
					<div id="history" className="mb-24 w-full">

						{ mess.map(e => (
							<pre key={e}>{e}</pre>
						)) }

					</div>

					<input className="text-2xl px-4 py-3 text-left text-white placeholder:text-white rounded-xl from-purple-300 to-purple-300/[0.9] bg-gradient-to-tl" placeholder="Tu pisz..." name="name" value={ input } onChange={ onChangeHandler } type="text" />
					<input className="text-2xl px-4 py-3 text-left text-white placeholder:text-white rounded-xl from-purple-300 to-purple-300/[0.9] bg-gradient-to-tl" placeholder="Twoje imie..." name="asd" value={ input2 } onChange={ onChangeHandler2 } type="text" />
					<button onClick={ btnHandler } className="bg-purple-300 text-white font-rubikbold px-5 py-4 rounded-xl ml-5">Wyślij</button>
					<button onClick={ clearHandler } className="bg-purple-300 text-white font-rubikbold px-5 py-4 rounded-xl ml-5">Clear</button>
				</div>
			</div>
		</>
	)
}
