import Head from 'next/head'
import { useEffect, useState } from 'react'
import { io } from "socket.io-client"

export default function LandingPage() {

  let socket = io();

  const [input, setInput] = useState('');

  const socketInitializer = async () => {

    await fetch('/api/socket');

    socket.on('connect', () => {
      console.log('connected');
    })

    socket.on('update-input', msg => {
      setInput(msg);
    })

    return null

  }

  const onChangeHandler = (e: any) => {

    setInput(e.target.value);
    socket.emit('input-change', e.target.value);

  }

  useEffect(() => {

    socketInitializer();

  }, [])
  
  return (	
		<>
			<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
			</Head>
      <div className="flex w-full h-full">
        <input className="mx-auto my-24 text-2xl text-center rounded-xl border-green-900 border-[5px]" placeholder="Tu pisz..." name="name" value={ input } onChange={ onChangeHandler } type="text" />
      </div>
		</>
	)
}
