import { XlContainer, SmContainer, MdContainer, LgContainer } from '../components/Global/Containers'
import Us from '../components/Us/Us'
import Head from 'next/head'
import Info from '../components/Info/Info'

export default function LandingPage() {
  return (	
		<>
			<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
			</Head>
		</>
	)
}
